<a href="https://colab.research.google.com/github/ShaijoGeorge/PythonPrograms/blob/main/07012022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
t(5)

25

In [5]:
seq=[1,2,3,4,5]

In [6]:
  t=lambda var:var**2

In [7]:
t(5)

25

In [8]:
list(map(lambda num:num**3,seq))

[1, 8, 27, 64, 125]

In [9]:
list(filter(lambda num:num%2==0,seq))

[2, 4]

In [10]:
#METHODS

In [11]:
s='Hello My Name is Shaijo'

In [12]:
s.upper()

'HELLO MY NAME IS SHAIJO'

In [13]:
s.lower()

'hello my name is shaijo'

In [15]:
s.split()

['Hello', 'My', 'Name', 'is', 'Shaijo']

In [16]:
tweet='Go Sports! #Sports'

In [17]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [18]:
tweet.split('#')[1]

'Sports'

In [19]:
tweet.split('#')[0]

'Go Sports! '

In [20]:
d={'k1':1,'k2':2}

In [21]:
d.keys()

dict_keys(['k1', 'k2'])

In [22]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [23]:
d.values()

dict_values([1, 2])

In [24]:
lst=[1,2,3]

In [25]:
lst.pop()

3

In [26]:
lst

[1, 2]

In [28]:
lst.append(5)

In [29]:
lst

[1, 2, 5]

In [30]:
lst.pop(1)

2

In [31]:
lst

[1, 5]

In [32]:
x=[(2,3),(4,5),(6,7)]

In [33]:
x[0]

(2, 3)

In [34]:
x[0][1]

3

In [36]:
for item in x:
  print(item)

(2, 3)
(4, 5)
(6, 7)


In [37]:
for(a,b) in x:
  print(a)

2
4
6


In [38]:
for(a,b) in x:
  print(b)

3
5
7


In [40]:
for(a,b) in x:
  print(a)
  print(b)

2
3
4
5
6
7


In [42]:
#Python Data Analysis Library - Numpy

In [43]:
my_list=[1,2,3]

In [44]:
import numpy as np

In [45]:
arr=np.array(my_list)

In [46]:
arr

array([1, 2, 3])

In [47]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [48]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [52]:
np.zeros(3)

array([0., 0., 0.])

In [53]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.random.rand()

0.938037206658086

In [61]:
np.random.rand(5,5)

array([[0.54470817, 0.97302388, 0.71982313, 0.14191559, 0.88249846],
       [0.64462476, 0.25585586, 0.3361386 , 0.74988329, 0.11885262],
       [0.88929072, 0.90157018, 0.87855209, 0.93288673, 0.09032914],
       [0.01247816, 0.49823637, 0.99325914, 0.46411695, 0.51054687],
       [0.28489545, 0.75105192, 0.49141525, 0.90920863, 0.79778506]])

In [65]:
np.random.randn(2) #Standard Normal Distribution

array([-0.27426079, -0.73842401])

In [63]:
np.random.randint(1,100)

76

In [64]:
np.random.randint(1,100,10)

array([52, 39, 13, 48, 61, 83, 64,  1, 39, 90])

In [66]:
arr=np.arange(25)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
ranarr=np.random.randint(0,50,5)

In [72]:
ranarr.max()

48

In [73]:
ranarr.min()

1

In [74]:
ranarr.argmax()

1

In [75]:
ranarr.argmin()

0

In [76]:
arr.shape

(25,)

In [77]:
arr1=arr.reshape(5,5)

In [78]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr1.shape

(5, 5)

In [80]:
arr.dtype

dtype('int64')